# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  chatgpt-review:
    name: ChatGPT Review
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' }}
    steps:
    - uses: lcxznpy/ChatGPT-Reviewer@my_branch
      name: ChatGPT Review
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACTION }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      with:
        model: "gpt-3.5-turbo"
        temperature: 0.2
        review_per_file: false
        comment_per_file: false     
