name: Delete branch on PR Merge

on:
  pull_request:
    types: closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
    - name:  Delete Branch
      if: github.event.pull_request.merged == true && github.event.pull_request.labels == Grafana-Dashboard-json
      uses: github-developer/github-action-delete-branch@releases/v1
      with:
        branch: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.TOKEN_ACTION }}
