name: Delete branch on PR Merge

on:
  pull_request:
    types: closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    env:
      Label: "Grafana-Dashboard-json"
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name:  Delete Branch
      if: github.event.pull_request.merged == true && github.event.pull_request.labels == ${{ env.Label }}
      uses: github-developer/github-action-delete-branch@releases/v1
      with:
        branch: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.TOKEN_ACTION }}
