name: MOC-565

on:
  workflow_dispatch:
    inputs:
      start-time:
          description: 'start-time'
          default: '2020-01-01T00:00:00Z'
          required: true
          type: string
      end-time:
          description: 'end-time'
          default: '2020-01-01T00:00:00Z'
          required: true
          type: string
      tag:
          description: 'tag_name or tag_sha'
          default: '2020-01-01T00:00:00Z'
          required: true
          type: string
jobs:
  Statistic-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Open issue numbers
        run: |
          so=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_ACTION}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/lcxznpy/asdf/issues?state=open&since=${{ inputs.start-time}}" | jq length)
          eo=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_ACTION}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/lcxznpy/asdf/issues?state=open&since=${{ inputs.end-time}}" | jq length)
          echo $(expr $so - $eo)
      - name: Get Close issue numbers
        run: |
          sc=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_ACTION}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/lcxznpy/asdf/issues?state=closed&since=${{ inputs.start-time}}" | jq length)
          ec=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_ACTION}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/lcxznpy/asdf/issues?state=closed&since=${{ inputs.end-time}}" | jq length)
          echo $(expr $sc - $ec)
      - name: Get tag issue numbers
        run: |
          tag_time=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $token" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$repo/commits/${{ inputs.tag}}" | jq '.commit.author.date')
          st=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_ACTION}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/lcxznpy/asdf/issues?state=closed&since=$tag_time" | jq length)
          # now_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          et=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_ACTION}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/lcxznpy/asdf/issues?state=closed&since=${{ inputs.end-time}}" | jq length)
          echo $(expr $st - $et)
